spring:
  application:
    name: currenct-transaction-api
  cloud:
    discovery.enabled: false
    service-registry.auto-registration.enabled: false

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    url: /open-api.yaml
  show-actuator: true


app:
  client:
    exchangeratesapi:
      name: exchangerates-api
      url: http://api.exchangeratesapi.io/v1/latest
      accessKey: da17c66a742789f80ab7fb04a15f01c9


