spring:
  application:
    name: currenct-transaction-api
  cloud:
    discovery.enabled: false
    service-registry.auto-registration.enabled: false

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

